const quotes = [
    "The happiness of your life depends upon the quality of your thoughts. - Marcus Aurelius",
    "You have power over your mind - not outside events. Realize this, and you will find strength. - Marcus Aurelius",
    "Dwell on the beauty of life. Watch the stars, and see yourself running with them. - Marcus Aurelius",
    "The best revenge is to be unlike him who performed the injury. - Marcus Aurelius",
    "It is not death that a man should fear, but he should fear never beginning to live. - Marcus Aurelius",
    "If it is not right, do not do it, if it is not true, do not say it. - Marcus Aurelius",
    "The soul becomes dyed with the color of its thoughts. - Marcus Aurelius",
    "The only wealth which you will keep forever is the wealth you have given away. - Marcus Aurelius",
    "Very little is needed to make a happy life; it is all within yourself, in your way of thinking. - Marcus Aurelius",
    "The universe is change; our life is what our thoughts make it. - Marcus Aurelius",
    "He who fears death will never do anything worth of a man who is alive. - Seneca",
    "Sometimes even to live is an act of courage. - Seneca",
    "We suffer more often in imagination than in reality. - Seneca",
    "It is the power of the mind to be unconquerable. - Seneca",
    "He who has injured thee was either stronger or weaker than thee. If weaker, spare him; if stronger, spare thyself. - Seneca",
    "Difficulties strengthen the mind, as labor does the body. - Seneca",
    "He suffers more than necessary, who suffers before it is necessary. - Seneca",
    "True happiness is to enjoy the present, without anxious dependence upon the future. - Seneca",
    "Luck is what happens when preparation meets opportunity. - Seneca",
    "Begin at once to live, and count each separate day as a separate life. - Seneca",
    "Man conquers the world by conquering himself. - Zeno of Citium",
    "Well-being is realized by small steps, but is truly no small thing. - Zeno of Citium",
    "No evil is honorable: but death is honorable; therefore death is not evil. - Zeno of Citium",
    "Steel your sensibilities, so that life shall hurt you as little as possible. - Zeno of Citium",
    "Happiness is a good flow of life. - Zeno of Citium",
    "The goal of life is living in agreement with nature. - Zeno of Citium",
    "We have two ears and one mouth, so we should listen more than we say. - Zeno of Citium",
    "If you lay violent hands on me, you’ll have my body, but my mind will remain with Stilpo. - Zeno of Citium",
    "Fate leads the willing, and drags along the reluctant. - Cleanthes",
    "Lead me, O Zeus, and thou, O Destiny, wherever you have assigned me. - Cleanthes",
    "He has the most who is content with the least. - Diogenes",
    "It is the privilege of the gods to want nothing, and of godlike men to want little. - Diogenes",
    "I am not an Athenian or a Greek, but a citizen of the world. - Diogenes",
    "He who is not a good servant will not be a good master. - Plato",
    "Courage is knowing what not to fear. - Plato",
    "The greatest wealth is to live content with little. - Plato",
    "The beginning is the most important part of the work. - Plato",
    "Those who are hardest to love need it the most. - Plato",
    "I judge you unfortunate because you have never lived through misfortune. You have passed through life without an opponent—no one can ever know what you are capable of, not even you. - Seneca",
    "If you want to improve, be content to be thought foolish and stupid. - Epictetus",
    "Don’t explain your philosophy. Embody it. - Epictetus",
    "First say to yourself what you would be; and then do what you have to do. - Epictetus",
    "If anyone tells you that a certain person speaks ill of you, do not make excuses about what is said of you but answer: He was ignorant of my other faults, else he would not have mentioned these alone. - Epictetus",
    "No man is free who is not master of himself. - Epictetus",
    "It’s not what happens to you, but how you react to it that matters. - Epictetus",
    "Wealth consists not in having great possessions, but in having few wants. - Epictetus",
    "Seek not the good in external things; seek it in yourselves. - Epictetus",
    "He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has. - Epictetus",
    "Circumstances don’t make the man, they only reveal him to himself. - Epictetus",
    "We are more often frightened than hurt, and we suffer more from imagination than from reality. - Seneca",
    "It is not the man who has too little, but the man who craves more, that is poor. - Seneca",
    "He who is brave is free. - Seneca",
    "No man was ever wise by chance. - Seneca",
    "Throw me to the wolves and I will return leading the pack. - Seneca",
    "While we wait for life, life passes. - Seneca",
    "To wish to be well is a part of becoming well. - Seneca",
    "Associate with people who are likely to improve you. - Seneca",
    "Let us say what we feel, and feel what we say; let speech harmonize with life. - Seneca",
    "A gem cannot be polished without friction, nor a man perfected without trials. - Seneca",
    "To be even-minded is the greatest virtue. - Heraclitus",
    "Character is destiny. - Heraclitus",
    "There is nothing permanent except change. - Heraclitus",
    "No man ever steps in the same river twice, for it’s not the same river and he’s not the same man. - Heraclitus",
    "Day by day, what you do is who you become. - Heraclitus",
    "Self-control is strength. Right thought is mastery. Calmness is power. - James Allen",
    "You will find rest from vain fancies if you perform every act in life as though it were your last. - Marcus Aurelius",
    "The things you think about determine the quality of your mind. - Marcus Aurelius",
    "Accept whatever comes to you woven in the pattern of your destiny, for what could more aptly fit your needs? - Marcus Aurelius",
    "Waste no more time arguing about what a good man should be. Be one. - Marcus Aurelius",
    "The best answer to anger is silence. - Marcus Aurelius",
    "Nothing happens to any man that he is not formed by nature to bear. - Marcus Aurelius",
    "A man’s worth is no greater than his ambitions. - Marcus Aurelius",
    "If someone is able to show me that what I think or do is not right, I will happily change, for I seek the truth, by which no one was ever truly harmed. The one who is harmed is the one who abides in deceit and ignorance. - Marcus Aurelius",
    "Remember that very little is needed to make a happy life. - Marcus Aurelius",
    "Perfection of character: to live your last day, every day, without frenzy, or sloth, or pretense. - Marcus Aurelius",
    // Add more quotes here to reach 1000
];

// Function to display a random quote
function displayRandomQuote() {
    const quoteElement = document.getElementById("quote");
    const randomIndex = Math.floor(Math.random() * quotes.length);
    quoteElement.textContent = quotes[randomIndex];
}

// Display a random quote on page load
displayRandomQuote();
